# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a1bdd0fff01315f3c7b83fd4b746015aebf8b018f4628aea48eeb1b6f6cebfa5a96f0c5d1800b4675167d9ae655742c4f3716e5f374f2ca016719e940b7d43d0

test:
  secret_key_base: 253b0266a655deb49f36f4b9221301abf06076a79b9c24365caddeeff434dc8f9fdc0ec699e939eeb9641424b308a379c620e57354ff35980240c91106cc2557

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
